<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-P7UT9DO" failures="0" tests="5" name="com.testng.TimeoutException_Test" time="3.215" errors="1" timestamp="2024-02-15T05:13:33 IST" skipped="0">
  <testcase classname="com.testng.TimeoutException_Test" name="twitterLogin" time="2.109">
    <error message="Method com.testng.TimeoutException_Test.twitterLogin() didn&#039;t finish within the time-out 2000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.TimeoutException_Test.twitterLogin() didn't finish within the time-out 2000
at java.base@11.0.20/java.lang.Thread.sleep(Native Method)
at app//com.testng.TimeoutException_Test.twitterLogin(TimeoutException_Test.java:9)
at java.base@11.0.20/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@11.0.20/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base@11.0.20/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@11.0.20/java.lang.reflect.Method.invoke(Method.java:566)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@11.0.20/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@11.0.20/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@11.0.20/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@11.0.20/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- twitterLogin -->
  <testcase classname="com.testng.TimeoutException_Test" name="pinterestLogin" time="0.036"/>
  <testcase classname="com.testng.TimeoutException_Test" name="redditLogin" time="0.025"/>
  <testcase classname="com.testng.TimeoutException_Test" name="yahooLogin" time="1.022"/>
  <testcase classname="com.testng.TimeoutException_Test" name="gmailLogin" time="0.023"/>
</testsuite> <!-- com.testng.TimeoutException_Test -->
